"""initial migration

Revision ID: 00aa3dcb5e43
Revises: 
Create Date: 2025-10-29 19:06:36.065682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00aa3dcb5e43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_carros_carro_id'), 'carros', ['carro_id'], unique=False)
    op.alter_column('cliente_carro', 'color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_cliente_carro_cliente_carro_id'), 'cliente_carro', ['cliente_carro_id'], unique=False)
    op.alter_column('clientes', 'correo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('clientes_correo_key'), 'clientes', type_='unique')
    op.create_index(op.f('ix_clientes_cliente_id'), 'clientes', ['cliente_id'], unique=False)
    op.alter_column('pieza_taller', 'precio_compra',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pieza_taller', 'precio_venta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('piezas', sa.Column('nombre_pieza', sa.String(length=100), nullable=False))
    op.alter_column('piezas', 'marca',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('piezas', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('piezas', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_piezas_pieza_id'), 'piezas', ['pieza_id'], unique=False)
    op.drop_column('piezas', 'nombre')
    op.alter_column('talleres', 'direccion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('talleres', 'horario_apertura',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('talleres', 'horario_cierre',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_talleres_taller_id'), 'talleres', ['taller_id'], unique=False)
    op.add_column('trabajo_usuarios', sa.Column('rol_trabajo', sa.String(length=100), nullable=False))
    op.drop_column('trabajo_usuarios', 'rol_en_trabajo')
    op.add_column('trabajos', sa.Column('descripcion_servicio', sa.String(length=255), nullable=True))
    op.add_column('trabajos', sa.Column('fecha_fin', sa.String(length=20), nullable=True))
    op.alter_column('trabajos', 'facturo',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trabajos', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trabajos_trabajo_id'), 'trabajos', ['trabajo_id'], unique=False)
    op.drop_column('trabajos', 'descripcion')
    op.drop_column('trabajos', 'fecha_final')
    op.drop_column('trabajos', 'garantia')
    op.alter_column('usuarios', 'correo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('usuarios', 'hashpassword',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.drop_constraint(op.f('usuarios_correo_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_usuario_id'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_correo_key'), 'usuarios', ['correo'], postgresql_nulls_not_distinct=False)
    op.alter_column('usuarios', 'hashpassword',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'correo',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('trabajos', sa.Column('garantia', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('trabajos', sa.Column('fecha_final', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trabajos', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trabajos_trabajo_id'), table_name='trabajos')
    op.alter_column('trabajos', 'fecha_inicio',
               existing_type=sa.String(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trabajos', 'facturo',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('trabajos', 'fecha_fin')
    op.drop_column('trabajos', 'descripcion_servicio')
    op.add_column('trabajo_usuarios', sa.Column('rol_en_trabajo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('trabajo_usuarios', 'rol_trabajo')
    op.drop_index(op.f('ix_talleres_taller_id'), table_name='talleres')
    op.alter_column('talleres', 'horario_cierre',
               existing_type=sa.String(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('talleres', 'horario_apertura',
               existing_type=sa.String(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('talleres', 'direccion',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('piezas', sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_piezas_pieza_id'), table_name='piezas')
    op.alter_column('piezas', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('piezas', 'descripcion',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('piezas', 'marca',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('piezas', 'nombre_pieza')
    op.alter_column('pieza_taller', 'precio_venta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pieza_taller', 'precio_compra',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_clientes_cliente_id'), table_name='clientes')
    op.create_unique_constraint(op.f('clientes_correo_key'), 'clientes', ['correo'], postgresql_nulls_not_distinct=False)
    op.alter_column('clientes', 'correo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_cliente_carro_cliente_carro_id'), table_name='cliente_carro')
    op.alter_column('cliente_carro', 'color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_carros_carro_id'), table_name='carros')
    # ### end Alembic commands ###
