"""Added createdat/updatedat to cars

Revision ID: 09e05065824b
Revises: 1ce9fd71484e
Create Date: 2025-11-07 11:12:40.970375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e05065824b'
down_revision: Union[str, Sequence[str], None] = '1ce9fd71484e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('cars', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'updated_at')
    op.drop_column('cars', 'created_at')
    # ### end Alembic commands ###
