"""removed pseudonimo

Revision ID: 6b6170e7988b
Revises: 00aa3dcb5e43
Create Date: 2025-10-29 19:10:49.039892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6170e7988b'
down_revision: Union[str, Sequence[str], None] = '00aa3dcb5e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'pseudonimo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('pseudonimo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
