"""added trabajo_trabajadores table

Revision ID: 7612bf8ded24
Revises: e70904fe28f8
Create Date: 2025-10-29 19:21:18.391472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7612bf8ded24'
down_revision: Union[str, Sequence[str], None] = 'e70904fe28f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajo_trabajadores',
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('rol_trabajo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.trabajador_id'], ),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.trabajo_id'], ),
    sa.PrimaryKeyConstraint('trabajo_id', 'trabajador_id', name='trabajo_usuarios_pk')
    )
    op.drop_table('trabajo_usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajo_usuarios',
    sa.Column('trabajo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rol_trabajo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.trabajo_id'], name=op.f('trabajo_usuarios_trabajo_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], name=op.f('trabajo_usuarios_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('trabajo_id', 'usuario_id', name=op.f('trabajo_usuarios_pkey'))
    )
    op.drop_table('trabajo_trabajadores')
    # ### end Alembic commands ###
