"""initial migration

Revision ID: 7d5b8f2e58ea
Revises: 
Create Date: 2025-10-30 09:45:49.617781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d5b8f2e58ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carros',
    sa.Column('carro_id', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('carro_id')
    )
    op.create_index(op.f('ix_carros_carro_id'), 'carros', ['carro_id'], unique=False)
    op.create_table('piezas',
    sa.Column('pieza_id', sa.Integer(), nullable=False),
    sa.Column('nombre_pieza', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('pieza_id')
    )
    op.create_index(op.f('ix_piezas_pieza_id'), 'piezas', ['pieza_id'], unique=False)
    op.create_table('talleres',
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('nombre_taller', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('horario_apertura', sa.String(length=20), nullable=True),
    sa.Column('horario_cierre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('taller_id')
    )
    op.create_index(op.f('ix_talleres_taller_id'), 'talleres', ['taller_id'], unique=False)
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], ),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_index(op.f('ix_clientes_cliente_id'), 'clientes', ['cliente_id'], unique=False)
    op.create_table('pieza_carro',
    sa.Column('carro_id', sa.Integer(), nullable=False),
    sa.Column('pieza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carro_id'], ['carros.carro_id'], ),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas.pieza_id'], ),
    sa.PrimaryKeyConstraint('carro_id', 'pieza_id', name='carro_piezas_pk')
    )
    op.create_table('pieza_taller',
    sa.Column('pieza_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas.pieza_id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], ),
    sa.PrimaryKeyConstraint('pieza_id', 'taller_id', name='pieza_taller_pk')
    )
    op.create_table('trabajadores',
    sa.Column('trabajador_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=False),
    sa.Column('pseudonimo', sa.String(length=50), nullable=True),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], ),
    sa.PrimaryKeyConstraint('trabajador_id')
    )
    op.create_index(op.f('ix_trabajadores_trabajador_id'), 'trabajadores', ['trabajador_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('rol', postgresql.ENUM('admin', 'gerente', 'trabajador', name='rol_enum'), nullable=False),
    sa.Column('hashpassword', sa.String(length=60), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    op.create_table('cliente_carro',
    sa.Column('cliente_carro_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('carro_id', sa.Integer(), nullable=False),
    sa.Column('placas', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['carro_id'], ['carros.carro_id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.PrimaryKeyConstraint('cliente_carro_id')
    )
    op.create_index(op.f('ix_cliente_carro_cliente_carro_id'), 'cliente_carro', ['cliente_carro_id'], unique=False)
    op.create_table('trabajos',
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('cliente_carro_id', sa.Integer(), nullable=False),
    sa.Column('facturo', sa.String(length=100), nullable=False),
    sa.Column('descripcion_servicio', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.String(length=20), nullable=False),
    sa.Column('fecha_fin', sa.String(length=20), nullable=True),
    sa.Column('estado', postgresql.ENUM('pendiente', 'en_proceso', 'completado', name='estado_enum'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_carro_id'], ['cliente_carro.cliente_carro_id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], ),
    sa.PrimaryKeyConstraint('trabajo_id')
    )
    op.create_index(op.f('ix_trabajos_trabajo_id'), 'trabajos', ['trabajo_id'], unique=False)
    op.create_table('trabajo_piezas',
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('pieza_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_usada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas.pieza_id'], ),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.trabajo_id'], ),
    sa.PrimaryKeyConstraint('trabajo_id', 'pieza_id', name='trabajo_piezas_pk')
    )
    op.create_table('trabajo_trabajadores',
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('rol_trabajo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.trabajador_id'], ),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.trabajo_id'], ),
    sa.PrimaryKeyConstraint('trabajo_id', 'trabajador_id', name='trabajo_usuarios_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajo_trabajadores')
    op.drop_table('trabajo_piezas')
    op.drop_index(op.f('ix_trabajos_trabajo_id'), table_name='trabajos')
    op.drop_table('trabajos')
    op.drop_index(op.f('ix_cliente_carro_cliente_carro_id'), table_name='cliente_carro')
    op.drop_table('cliente_carro')
    op.drop_index(op.f('ix_usuarios_usuario_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_trabajadores_trabajador_id'), table_name='trabajadores')
    op.drop_table('trabajadores')
    op.drop_table('pieza_taller')
    op.drop_table('pieza_carro')
    op.drop_index(op.f('ix_clientes_cliente_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_talleres_taller_id'), table_name='talleres')
    op.drop_table('talleres')
    op.drop_index(op.f('ix_piezas_pieza_id'), table_name='piezas')
    op.drop_table('piezas')
    op.drop_index(op.f('ix_carros_carro_id'), table_name='carros')
    op.drop_table('carros')
    # ### end Alembic commands ###
