"""changed db to english

Revision ID: 7fafc04716a4
Revises: c31eafd81789
Create Date: 2025-10-30 13:12:17.956707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fafc04716a4'
down_revision: Union[str, Sequence[str], None] = 'c31eafd81789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_index(op.f('ix_cars_car_id'), 'cars', ['car_id'], unique=False)
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_index(op.f('ix_parts_part_id'), 'parts', ['part_id'], unique=False)
    op.create_table('workshops',
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('workshop_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('opening_hours', sa.String(length=20), nullable=True),
    sa.Column('closing_hours', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('workshop_id')
    )
    op.create_index(op.f('ix_workshops_workshop_id'), 'workshops', ['workshop_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_table('part_car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('car_id', 'part_id', name='car_parts_pk')
    )
    op.create_table('part_workshop',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], ),
    sa.PrimaryKeyConstraint('part_id', 'workshop_id', name='part_workshop_pk')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', postgresql.ENUM('admin', 'manager', 'worker', name='role_enum'), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('workers',
    sa.Column('worker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_workers_worker_id'), 'workers', ['worker_id'], unique=False)
    op.create_table('customer_car',
    sa.Column('customer_car_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('customer_car_id')
    )
    op.create_index(op.f('ix_customer_car_customer_car_id'), 'customer_car', ['customer_car_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('customer_car_id', sa.Integer(), nullable=False),
    sa.Column('invoice', sa.String(length=100), nullable=False),
    sa.Column('service_description', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'in_progress', 'completed', name='status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['customer_car_id'], ['customer_car.customer_car_id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_table('job_parts',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'part_id', name='job_parts_pk')
    )
    op.create_table('job_workers',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('job_role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'worker_id', name='job_workers_pk')
    )
    op.drop_index(op.f('ix_carros_carro_id'), table_name='carros')
    op.execute("DROP TABLE carros CASCADE;")
    op.execute("DROP TYPE IF EXISTS estado_enum CASCADE;")
    op.execute("DROP TABLE pieza_carro CASCADE;")
    op.execute("DROP TABLE pieza_taller CASCADE;")
    op.execute("DROP TABLE cliente_carro CASCADE;")
    op.execute("DROP TABLE talleres CASCADE;")
    op.execute("DROP TABLE clientes CASCADE;")
    op.execute("DROP TABLE piezas CASCADE;")
    op.execute("DROP TYPE IF EXISTS rol_enum CASCADE;")
    op.execute("DROP TABLE usuarios CASCADE;")
    op.execute("DROP TABLE trabajo_piezas CASCADE;")
    op.execute("DROP TABLE trabajadores CASCADE;")
    op.execute("DROP TABLE trabajos CASCADE;")
    op.execute("DROP TABLE trabajo_trabajadores CASCADE;")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pieza_taller',
    sa.Column('pieza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_compra', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_venta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas.pieza_id'], name=op.f('pieza_taller_pieza_id_fkey')),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], name=op.f('pieza_taller_taller_id_fkey')),
    sa.PrimaryKeyConstraint('pieza_id', 'taller_id', name=op.f('pieza_taller_pk'))
    )
    op.create_table('trabajo_trabajadores',
    sa.Column('trabajo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trabajador_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rol_trabajo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.trabajador_id'], name=op.f('trabajo_trabajadores_trabajador_id_fkey')),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.trabajo_id'], name=op.f('trabajo_trabajadores_trabajo_id_fkey')),
    sa.PrimaryKeyConstraint('trabajo_id', 'trabajador_id', name=op.f('trabajo_usuarios_pk'))
    )
    op.create_table('trabajos',
    sa.Column('trabajo_id', sa.INTEGER(), server_default=sa.text("nextval('trabajos_trabajo_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('taller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_carro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('facturo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion_servicio', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estado', postgresql.ENUM('pendiente', 'en_proceso', 'completado', name='estado_enum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_carro_id'], ['cliente_carro.cliente_carro_id'], name='trabajos_cliente_carro_id_fkey'),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], name='trabajos_taller_id_fkey'),
    sa.PrimaryKeyConstraint('trabajo_id', name='trabajos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_trabajos_trabajo_id'), 'trabajos', ['trabajo_id'], unique=False)
    op.create_table('trabajadores',
    sa.Column('trabajador_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('puesto', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pseudonimo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('taller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], name=op.f('trabajadores_taller_id_fkey')),
    sa.PrimaryKeyConstraint('trabajador_id', name=op.f('trabajadores_pkey'))
    )
    op.create_index(op.f('ix_trabajadores_trabajador_id'), 'trabajadores', ['trabajador_id'], unique=False)
    op.create_table('trabajo_piezas',
    sa.Column('trabajo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pieza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_usada', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas.pieza_id'], name=op.f('trabajo_piezas_pieza_id_fkey')),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.trabajo_id'], name=op.f('trabajo_piezas_trabajo_id_fkey')),
    sa.PrimaryKeyConstraint('trabajo_id', 'pieza_id', name=op.f('trabajo_piezas_pk'))
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rol', postgresql.ENUM('admin', 'gerente', 'trabajador', name='rol_enum'), autoincrement=False, nullable=False),
    sa.Column('hashpassword', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('taller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], name=op.f('usuarios_taller_id_fkey')),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    op.create_table('piezas',
    sa.Column('pieza_id', sa.INTEGER(), server_default=sa.text("nextval('piezas_pieza_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre_pieza', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pieza_id', name='piezas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_piezas_pieza_id'), 'piezas', ['pieza_id'], unique=False)
    op.create_table('clientes',
    sa.Column('cliente_id', sa.INTEGER(), server_default=sa.text("nextval('clientes_cliente_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('taller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], name='clientes_taller_id_fkey'),
    sa.PrimaryKeyConstraint('cliente_id', name='clientes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_clientes_cliente_id'), 'clientes', ['cliente_id'], unique=False)
    op.create_table('talleres',
    sa.Column('taller_id', sa.INTEGER(), server_default=sa.text("nextval('talleres_taller_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre_taller', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('horario_apertura', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('horario_cierre', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('taller_id', name='talleres_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_talleres_taller_id'), 'talleres', ['taller_id'], unique=False)
    op.create_table('cliente_carro',
    sa.Column('cliente_carro_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placas', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['carro_id'], ['carros.carro_id'], name=op.f('cliente_carro_carro_id_fkey')),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], name=op.f('cliente_carro_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('cliente_carro_id', name=op.f('cliente_carro_pkey'))
    )
    op.create_index(op.f('ix_cliente_carro_cliente_carro_id'), 'cliente_carro', ['cliente_carro_id'], unique=False)
    op.create_table('pieza_carro',
    sa.Column('carro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pieza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carro_id'], ['carros.carro_id'], name=op.f('pieza_carro_carro_id_fkey')),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas.pieza_id'], name=op.f('pieza_carro_pieza_id_fkey')),
    sa.PrimaryKeyConstraint('carro_id', 'pieza_id', name=op.f('carro_piezas_pk'))
    )
    op.create_table('carros',
    sa.Column('carro_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('año', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('carro_id', name=op.f('carros_pkey'))
    )
    op.create_index(op.f('ix_carros_carro_id'), 'carros', ['carro_id'], unique=False)
    op.drop_table('job_workers')
    op.drop_table('job_parts')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_customer_car_customer_car_id'), table_name='customer_car')
    op.drop_table('customer_car')
    op.drop_index(op.f('ix_workers_worker_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('part_workshop')
    op.drop_table('part_car')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_workshops_workshop_id'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_parts_part_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_cars_car_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
