"""Fixed createdAt in users

Revision ID: 8fde31b5f7f1
Revises: 35a9bf8bbab7
Create Date: 2025-11-02 13:53:21.768491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fde31b5f7f1'
down_revision: Union[str, Sequence[str], None] = '35a9bf8bbab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
