"""Changed created columns to datetime

Revision ID: 9876e7f9adee
Revises: a27dae8789a7
Create Date: 2025-11-02 13:57:27.956438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9876e7f9adee'
down_revision: Union[str, Sequence[str], None] = 'a27dae8789a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use raw SQL with USING clause to convert string to timestamp
    # If existing data is NULL or empty, set to current timestamp
    op.execute("""
        ALTER TABLE customers 
        ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE 
        USING COALESCE(
            CASE 
                WHEN created_at IS NULL OR created_at = '' THEN NULL
                ELSE created_at::timestamp without time zone 
            END,
            NOW()
        )
    """)
    
    op.execute("""
        ALTER TABLE customers 
        ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE 
        USING COALESCE(
            CASE 
                WHEN updated_at IS NULL OR updated_at = '' THEN NULL
                ELSE updated_at::timestamp without time zone 
            END,
            NOW()
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
