"""added trabajadores table

Revision ID: e70904fe28f8
Revises: 6b6170e7988b
Create Date: 2025-10-29 19:17:39.913985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70904fe28f8'
down_revision: Union[str, Sequence[str], None] = '6b6170e7988b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('trabajador_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=False),
    sa.Column('pseudonimo', sa.String(length=50), nullable=True),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.taller_id'], ),
    sa.PrimaryKeyConstraint('trabajador_id')
    )
    op.create_index(op.f('ix_trabajadores_trabajador_id'), 'trabajadores', ['trabajador_id'], unique=False)
    op.drop_column('usuarios', 'telefono')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trabajadores_trabajador_id'), table_name='trabajadores')
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
